const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { Op } = require('sequelize');
const sequelize = require('../models/db');
const Employee = require('../models/employee');
const Company = require('../models/company');
const PerformanceReviewTemplate = require('../models/performanceReviewTemplate');
const EmployeePerformanceReport = require('../models/employeePerformanceReport');
const PerformanceReportVersion = require('../models/performanceReportVersion');
const PerformanceReportReplacementRequest = require('../models/performanceReportReplacementRequest');
const AuditLog = require('../models/auditLog');
const { TEMPLATE_ROOT } = require('../services/performanceReviewTemplateSeed');

const REVIEW_TYPES = new Set(['MID_YEAR', 'YEAR_END']);
const REVIEW_DETAILS = { MID_YEAR: { label: 'Mid-Year Performance Review', month: 'June' }, YEAR_END: { label: 'Year-End Performance Review', month: 'December' } };
const validYear = value => { const year = Number(value); return Number.isInteger(year) && year >= 2000 && year <= 2100 ? year : null; };
const employeeName = employee => [employee?.firstName, employee?.lastName].filter(Boolean).join(' ') || employee?.name || employee?.email || 'Unnamed employee';
async function currentEmployee(req) { if (req.user?.employeeId) { const employee = await Employee.findByPk(req.user.employeeId); if (employee) return employee; } return req.user?.email ? Employee.findOne({ where: { email: req.user.email } }) : null; }
async function companyForEmployee(employee) { const name = String(employee?.presentEmployer || '').trim(); return name ? Company.findOne({ where: { name } }) : null; }
function safeStoragePath(storageKey) { const resolved = path.resolve(TEMPLATE_ROOT, storageKey || ''); return resolved.startsWith(TEMPLATE_ROOT + path.sep) ? resolved : null; }
function removeFile(storageKey) { const filePath = safeStoragePath(storageKey); if (filePath && fs.existsSync(filePath)) fs.unlinkSync(filePath); }
function sendFile(res, storageKey, originalFilename, disposition = 'attachment') { const filePath = safeStoragePath(storageKey); if (!filePath || !fs.existsSync(filePath)) return res.status(404).json({ error: 'Performance review file is unavailable.' }); const filename = String(originalFilename || path.basename(filePath)).replace(/[\r\n"]/g, '_'); if (disposition === 'inline') { res.setHeader('Content-Disposition', `inline; filename="${filename}"`); return res.sendFile(filePath); } return res.download(filePath, filename); }
function serializeVersion(version) { return version ? { id: version.id, versionNumber: version.versionNumber, originalFilename: version.originalFilename, status: version.status, uploadedAt: version.uploadedAt, submittedAt: version.submittedAt } : null; }
function serializeSubmission(report, version) { return report?.status === 'SUBMITTED' ? { id: report.id, reviewType: report.reviewType, reviewYear: report.reviewYear, companyId: report.companyId, companyName: report.companyNameSnapshot, originalFilename: version?.originalFilename || report.originalFilename, status: report.status, submittedAt: report.submittedAt, currentVersion: serializeVersion(version) } : null; }
function serializeRequest(request) { return request ? { id: request.id, status: request.status, reason: request.reason, requestedAt: request.createdAt, reviewedAt: request.reviewedAt, consumedAt: request.consumedAt } : null; }
function fileValues(file, storageKey, storedFilename) { return { originalFilename: file.originalname, storedFilename, storageKey, mimeType: file.mimetype, fileSize: file.size, uploadedAt: new Date() }; }

exports.getMyReports = async (req, res) => {
  try {
    const employee = await currentEmployee(req); if (!employee) return res.status(404).json({ error: 'Employee profile not found.' });
    const company = await companyForEmployee(employee); if (!company) return res.json({ employeeId: employee.employee_id, company: null, availableYears: [], reviews: [], message: 'Your company association is not available. Please contact HR.' });
    const requestedYear = validYear(req.query.year) || new Date().getFullYear();
    const availableTemplates = await PerformanceReviewTemplate.findAll({ where: { companyId: company.id, isActive: true }, order: [['reviewYear', 'DESC'], ['reviewType', 'ASC'], ['version', 'DESC']] });
    const availableYears = [...new Set(availableTemplates.map(item => item.reviewYear))]; const reviewYear = availableYears.includes(requestedYear) ? requestedYear : (availableYears[0] || requestedYear); const templates = availableTemplates.filter(item => item.reviewYear === reviewYear);
    const reports = await EmployeePerformanceReport.findAll({ where: { employeeId: employee.employee_id, reviewYear } }); const reportIds = reports.map(item => item.id);
    const [versions, requests] = await Promise.all([reportIds.length ? PerformanceReportVersion.findAll({ where: { reportId: { [Op.in]: reportIds } }, order: [['versionNumber', 'DESC']] }) : [], reportIds.length ? PerformanceReportReplacementRequest.findAll({ where: { reportId: { [Op.in]: reportIds } }, order: [['created_at', 'DESC']] }) : []]);
    const reportByReview = new Map(reports.map(item => [item.reviewType, item])); const versionById = new Map(versions.map(item => [item.id, item])); const draftByReport = new Map(versions.filter(item => item.status === 'draft').map(item => [item.reportId, item])); const latestRequestByReport = new Map(); for (const item of requests) if (!latestRequestByReport.has(item.reportId)) latestRequestByReport.set(item.reportId, item);
    res.json({ employeeId: employee.employee_id, company: { id: company.id, name: company.name }, reviewYear, availableYears, reviews: templates.map(template => { const report = reportByReview.get(template.reviewType); return { templateId: template.id, reviewType: template.reviewType, reviewLabel: REVIEW_DETAILS[template.reviewType].label, reviewMonth: REVIEW_DETAILS[template.reviewType].month, reviewYear: template.reviewYear, templateFilename: template.originalFilename, reportId: report?.id || null, draft: serializeVersion(draftByReport.get(report?.id)), submission: serializeSubmission(report, versionById.get(report?.currentVersionId)), replacementRequest: serializeRequest(latestRequestByReport.get(report?.id)) }; }) });
  } catch (err) { res.status(500).json({ error: err.message }); }
};

exports.downloadMyTemplate = async (req, res) => { try { const employee = await currentEmployee(req); const template = await PerformanceReviewTemplate.findByPk(req.params.templateId); const company = await companyForEmployee(employee); if (!employee || !company || !template || !template.isActive || template.companyId !== company.id) return res.status(404).json({ error: 'Performance review template not found.' }); return sendFile(res, template.storageKey, template.originalFilename); } catch (err) { return res.status(500).json({ error: err.message }); } };
exports.downloadMySubmission = async (req, res) => { try { const employee = await currentEmployee(req); const report = await EmployeePerformanceReport.findByPk(req.params.submissionId); if (!employee || !report || report.employeeId !== employee.employee_id || report.status !== 'SUBMITTED') return res.status(404).json({ error: 'Performance review submission not found.' }); const version = await PerformanceReportVersion.findByPk(report.currentVersionId); return sendFile(res, version?.storageKey || report.storageKey, version?.originalFilename || report.originalFilename); } catch (err) { return res.status(500).json({ error: err.message }); } };

exports.uploadMyDraft = async (req, res) => {
  const tempKey = req.file?.storageKey;
  try {
    const reviewType = String(req.body.reviewType || '').toUpperCase(); const reviewYear = validYear(req.body.reviewYear); if (!req.file) return res.status(400).json({ error: 'Select a completed PDF document to upload.' }); if (!REVIEW_TYPES.has(reviewType) || !reviewYear) { removeFile(tempKey); return res.status(400).json({ error: 'A valid review type and review year are required.' }); }
    const employee = await currentEmployee(req); const company = await companyForEmployee(employee); if (!employee || !company) { removeFile(tempKey); return res.status(400).json({ error: 'Your company association is not available.' }); }
    const template = await PerformanceReviewTemplate.findOne({ where: { companyId: company.id, reviewType, reviewYear, isActive: true } }); if (!template) { removeFile(tempKey); return res.status(400).json({ error: 'The selected performance review template is not available for your company.' }); }
    const existing = await EmployeePerformanceReport.findOne({ where: { employeeId: employee.employee_id, reviewType, reviewYear } }); if (existing && existing.companyId !== company.id) { removeFile(tempKey); return res.status(409).json({ error: 'This historical review belongs to a previous company and cannot be replaced from your current company.' }); }
    let approvedRequest = null; if (existing?.status === 'SUBMITTED') { approvedRequest = await PerformanceReportReplacementRequest.findOne({ where: { reportId: existing.id, employeeId: employee.employee_id, status: 'approved' } }); if (!approvedRequest) { removeFile(tempKey); return res.status(403).json({ error: 'This submitted report is locked. Root Admin approval is required before replacement.' }); } }
    const storedFilename = `performance_${Date.now()}_${crypto.randomUUID()}${path.extname(req.file.originalname).toLowerCase()}`; const storageKey = path.posix.join('submissions', String(employee.employee_id), String(reviewYear), reviewType, storedFilename); const destination = safeStoragePath(storageKey); if (!destination) throw new Error('Invalid performance report storage path.'); fs.mkdirSync(path.dirname(destination), { recursive: true }); fs.renameSync(req.file.path, destination);
    let report; let draft; let oldDraftKey = null;
    try { await sequelize.transaction(async transaction => {
      report = existing || await EmployeePerformanceReport.create({ employeeId: employee.employee_id, companyId: company.id, companyNameSnapshot: company.name, templateId: template.id, reviewType, reviewYear, ...fileValues(req.file, storageKey, storedFilename), status: 'DRAFT', submittedAt: null, lockedAt: null }, { transaction });
      draft = await PerformanceReportVersion.findOne({ where: { reportId: report.id, status: 'draft' }, transaction, lock: transaction.LOCK.UPDATE }); const nextNumber = draft?.versionNumber || ((await PerformanceReportVersion.max('versionNumber', { where: { reportId: report.id }, transaction }) || 0) + 1); const values = { reportId: report.id, versionNumber: nextNumber, ...fileValues(req.file, storageKey, storedFilename), status: 'draft' };
      if (draft) { oldDraftKey = draft.storageKey; await draft.update(values, { transaction }); } else draft = await PerformanceReportVersion.create(values, { transaction });
      if (report.status === 'DRAFT') await report.update({ templateId: template.id, ...fileValues(req.file, storageKey, storedFilename), currentVersionId: draft.id }, { transaction });
      await AuditLog.create({ entity: 'EmployeePerformanceReport', entityId: report.id, action: existing?.status === 'SUBMITTED' ? 'replacement_draft_uploaded' : 'draft_uploaded', actorId: req.user.id, payload: { reviewType, reviewYear, originalFilename: req.file.originalname, requestId: approvedRequest?.id || null } }, { transaction });
    }); } catch (err) { removeFile(storageKey); throw err; }
    if (oldDraftKey && oldDraftKey !== storageKey) removeFile(oldDraftKey); return res.status(201).json({ reportId: report.id, draft: serializeVersion(draft) });
  } catch (err) { if (tempKey) removeFile(tempKey); return res.status(500).json({ error: err.message }); }
};

exports.submitMyReport = async (req, res) => {
  try {
    const employee = await currentEmployee(req); const reportId = Number(req.params.reportId); if (!employee || !Number.isInteger(reportId)) return res.status(400).json({ error: 'A valid performance report is required.' }); let result;
    await sequelize.transaction(async transaction => {
      const report = await EmployeePerformanceReport.findOne({ where: { id: reportId, employeeId: employee.employee_id }, transaction, lock: transaction.LOCK.UPDATE }); if (!report) throw Object.assign(new Error('Performance review report not found.'), { statusCode: 404 }); const draft = await PerformanceReportVersion.findOne({ where: { reportId: report.id, status: 'draft' }, transaction, lock: transaction.LOCK.UPDATE }); if (!draft) throw Object.assign(new Error('Upload a completed document before submitting.'), { statusCode: 400 });
      let replacementRequest = null; const isReplacement = report.status === 'SUBMITTED'; if (isReplacement) { replacementRequest = await PerformanceReportReplacementRequest.findOne({ where: { reportId: report.id, employeeId: employee.employee_id, status: 'approved' }, transaction, lock: transaction.LOCK.UPDATE }); if (!replacementRequest) throw Object.assign(new Error('This submitted report is locked. Root Admin approval is required.'), { statusCode: 403 }); }
      const priorVersion = report.currentVersionId ? await PerformanceReportVersion.findByPk(report.currentVersionId, { transaction, lock: transaction.LOCK.UPDATE }) : null; const now = new Date(); await draft.update({ status: 'submitted', submittedAt: now }, { transaction }); if (isReplacement && priorVersion && priorVersion.id !== draft.id) await priorVersion.update({ status: 'superseded', replacedAt: now }, { transaction }); await report.update({ originalFilename: draft.originalFilename, storedFilename: draft.storedFilename, storageKey: draft.storageKey, mimeType: draft.mimeType, fileSize: draft.fileSize, currentVersionId: draft.id, status: 'SUBMITTED', submittedAt: now, lockedAt: now }, { transaction }); if (replacementRequest) await replacementRequest.update({ status: 'consumed', consumedAt: now, replacementVersionId: draft.id }, { transaction }); await AuditLog.create({ entity: 'EmployeePerformanceReport', entityId: report.id, action: isReplacement ? 'replacement_submitted' : 'submitted', actorId: req.user.id, payload: { versionId: draft.id, reviewType: report.reviewType, reviewYear: report.reviewYear, replacementRequestId: replacementRequest?.id || null } }, { transaction }); result = { report, draft };
    });
    return res.json({ submission: serializeSubmission(result.report, result.draft) });
  } catch (err) { return res.status(err.statusCode || 500).json({ error: err.message }); }
};

exports.requestReplacement = async (req, res) => { try { const employee = await currentEmployee(req); const reportId = Number(req.params.reportId); const reason = String(req.body?.reason || '').trim(); if (!reason) return res.status(400).json({ error: 'Reason for replacement is required.' }); const report = await EmployeePerformanceReport.findOne({ where: { id: reportId, employeeId: employee?.employee_id, status: 'SUBMITTED' } }); if (!report) return res.status(404).json({ error: 'Submitted performance review report not found.' }); const active = await PerformanceReportReplacementRequest.findOne({ where: { reportId: report.id, status: { [Op.in]: ['pending', 'approved'] } } }); if (active) return res.status(409).json({ error: `A replacement request is already ${active.status} for this report.` }); const request = await PerformanceReportReplacementRequest.create({ employeeId: employee.employee_id, reportId: report.id, companyId: report.companyId, companyNameSnapshot: report.companyNameSnapshot, reviewType: report.reviewType, reviewYear: report.reviewYear, submittedVersionId: report.currentVersionId, reason, status: 'pending' }); await AuditLog.create({ entity: 'PerformanceReportReplacementRequest', entityId: request.id, action: 'replacement_requested', actorId: req.user.id, payload: { reportId: report.id, reason } }); return res.status(201).json({ request: serializeRequest(request) }); } catch (err) { if (err.name === 'SequelizeUniqueConstraintError') return res.status(409).json({ error: 'A replacement request is already pending or approved for this report.' }); return res.status(500).json({ error: err.message }); } };

exports.listForRootAdmin = async (req, res) => {
  try {
    const reviewYear = validYear(req.query.year) || new Date().getFullYear(); const reviewType = REVIEW_TYPES.has(String(req.query.reviewType || '').toUpperCase()) ? String(req.query.reviewType).toUpperCase() : null; const status = ['SUBMITTED', 'NOT_SUBMITTED'].includes(String(req.query.status || '').toUpperCase()) ? String(req.query.status).toUpperCase() : null; const companyId = Number.isInteger(Number(req.query.companyId)) ? Number(req.query.companyId) : null; const search = String(req.query.search || '').trim().toLowerCase();
    const [employees, companies, templates, reports, templateYears] = await Promise.all([Employee.findAll({ where: { presentEmployer: { [Op.ne]: null } }, order: [['firstName', 'ASC'], ['lastName', 'ASC'], ['name', 'ASC']] }), Company.findAll({ order: [['name', 'ASC']] }), PerformanceReviewTemplate.findAll({ where: { reviewYear, isActive: true }, order: [['companyId', 'ASC'], ['reviewType', 'ASC'], ['version', 'DESC']] }), EmployeePerformanceReport.findAll({ where: { reviewYear, status: 'SUBMITTED' }, order: [['submittedAt', 'DESC']] }), PerformanceReviewTemplate.findAll({ where: { isActive: true }, attributes: ['reviewYear'], group: ['review_year'], order: [['reviewYear', 'DESC']] })]);
    const versions = reports.length ? await PerformanceReportVersion.findAll({ where: { id: { [Op.in]: reports.map(report => report.currentVersionId).filter(Boolean) } } }) : []; const versionById = new Map(versions.map(item => [item.id, item])); const companyByName = new Map(companies.map(item => [item.name, item])); const templatesByCompany = new Map(); for (const template of templates) { const list = templatesByCompany.get(template.companyId) || []; if (!list.some(item => item.reviewType === template.reviewType)) list.push(template); templatesByCompany.set(template.companyId, list); }
    const reportByEmployeeReview = new Map(reports.map(item => [`${item.employeeId}:${item.reviewType}`, item])); const rows = []; for (const employee of employees) { const currentCompany = companyByName.get(String(employee.presentEmployer || '').trim()); if (!currentCompany) continue; for (const template of templatesByCompany.get(currentCompany.id) || []) { if (reviewType && template.reviewType !== reviewType) continue; const report = reportByEmployeeReview.get(`${employee.employee_id}:${template.reviewType}`); const rowCompanyId = report?.companyId || currentCompany.id; const rowCompanyName = report?.companyNameSnapshot || currentCompany.name; const rowStatus = report ? 'SUBMITTED' : 'NOT_SUBMITTED'; if (companyId && rowCompanyId !== companyId) continue; if (status && rowStatus !== status) continue; if (search && !`${employeeName(employee)} ${employee.email || ''} ${rowCompanyName}`.toLowerCase().includes(search)) continue; rows.push({ employeeId: employee.employee_id, employeeName: employeeName(employee), employeeEmail: employee.email || null, companyId: rowCompanyId, companyName: rowCompanyName, reviewType: template.reviewType, reviewLabel: REVIEW_DETAILS[template.reviewType].label, reviewYear, status: rowStatus, submission: serializeSubmission(report, versionById.get(report?.currentVersionId)) }); } }
    res.json({ reviewYear, availableYears: templateYears.map(item => item.reviewYear), companies: companies.map(item => ({ id: item.id, name: item.name })), rows });
  } catch (err) { res.status(500).json({ error: err.message }); }
};

async function rootReport(req, res, disposition) { try { const report = await EmployeePerformanceReport.findOne({ where: { id: req.params.submissionId, status: 'SUBMITTED' } }); if (!report) return res.status(404).json({ error: 'Performance review submission not found.' }); const version = await PerformanceReportVersion.findByPk(report.currentVersionId); return sendFile(res, version?.storageKey || report.storageKey, version?.originalFilename || report.originalFilename, disposition); } catch (err) { return res.status(500).json({ error: err.message }); } }
exports.downloadForRootAdmin = (req, res) => rootReport(req, res, 'attachment');
exports.previewForRootAdmin = (req, res) => rootReport(req, res, 'inline');
async function reviewReplacementRequest(req, res, status) { try { const request = await PerformanceReportReplacementRequest.findByPk(req.params.requestId); if (!request) return res.status(404).json({ error: 'Replacement request not found.' }); if (request.status !== 'pending') return res.status(409).json({ error: 'Replacement request has already been processed.' }); await request.update({ status, reviewedBy: req.user.id, reviewedAt: new Date() }); await AuditLog.create({ entity: 'PerformanceReportReplacementRequest', entityId: request.id, action: `replacement_${status}`, actorId: req.user.id, payload: { reportId: request.reportId } }); return res.json({ request: serializeRequest(request) }); } catch (err) { return res.status(500).json({ error: err.message }); } }
exports.approveReplacementRequest = (req, res) => reviewReplacementRequest(req, res, 'approved');
exports.rejectReplacementRequest = (req, res) => reviewReplacementRequest(req, res, 'rejected');
