import { useEffect, useState } from 'react';
import { FaDownload, FaEye } from 'react-icons/fa';
import AdminTypography from '../../components/admin/AdminTypography';
import { downloadProtectedPerformanceFile, getAdminPerformanceReports, getProtectedPerformanceBlob } from '../../api/performanceReports';

const initialFilters = { search: '', companyId: '', reviewType: '', status: '', year: new Date().getFullYear() };
const formatDate = value => value ? new Date(value).toLocaleString() : '—';

export default function EmployeePerformanceReports() {
  const [filters, setFilters] = useState(initialFilters); const [data, setData] = useState({ rows: [], companies: [], availableYears: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [preview, setPreview] = useState(null);
  const load = async activeFilters => { setLoading(true); setError(''); try { const params = Object.fromEntries(Object.entries(activeFilters).filter(([, value]) => value !== '')); const response = await getAdminPerformanceReports(params); setData(response.data); if (response.data.reviewYear && response.data.reviewYear !== activeFilters.year) setFilters(current => ({ ...current, year: response.data.reviewYear })); } catch (err) { setError(err?.response?.data?.error || 'Unable to load employee performance reports.'); } finally { setLoading(false); } };
  useEffect(() => { load(filters); }, []);
  const apply = event => { event.preventDefault(); load(filters); }; const clear = () => { setFilters(initialFilters); load(initialFilters); };
  const download = async row => { if (!row.submission) return; setError(''); try { await downloadProtectedPerformanceFile(`/performance-reports/admin/submissions/${row.submission.id}/download`, row.submission.originalFilename); } catch (err) { setError(err.message || 'Download failed.'); } };
  const startPreview = async row => { if (!row.submission) return; setError(''); try { const blob = await getProtectedPerformanceBlob(`/performance-reports/admin/submissions/${row.submission.id}/preview`); setPreview({ url: URL.createObjectURL(blob), filename: row.submission.originalFilename, isPdf: /\.pdf$/i.test(row.submission.originalFilename || '') }); } catch (err) { setError(err.message || 'Preview failed.'); } };
  const closePreview = () => { if (preview?.url) URL.revokeObjectURL(preview.url); setPreview(null); };
  const control = 'mt-1 h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
  return <main className="min-h-screen flex-1 bg-white p-8"><AdminTypography.h1 className="mb-2">Emp Performance Report</AdminTypography.h1><p className="mb-6 text-gray-600">Track employee performance review submissions by company, review cycle, and year.</p>
    {error && <div role="alert" className="mb-5 rounded border border-red-200 bg-red-50 px-4 py-3 text-red-700">{error}</div>}
    <form onSubmit={apply} className="mb-6 rounded-xl border border-gray-200 bg-slate-50 p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold text-gray-800">Filter Performance Reports</h2><span className="text-sm text-gray-500">Refine the employee review list</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5"><label className="text-sm font-medium text-gray-700">Search Employee<input value={filters.search} onChange={event => setFilters(current => ({ ...current, search: event.target.value }))} placeholder="Name or email" className={control} /></label><label className="text-sm font-medium text-gray-700">Company<select value={filters.companyId} onChange={event => setFilters(current => ({ ...current, companyId: event.target.value }))} className={control}><option value="">All Companies</option>{data.companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="text-sm font-medium text-gray-700">Review Type<select value={filters.reviewType} onChange={event => setFilters(current => ({ ...current, reviewType: event.target.value }))} className={control}><option value="">All Reviews</option><option value="MID_YEAR">Mid-Year</option><option value="YEAR_END">Year-End</option></select></label><label className="text-sm font-medium text-gray-700">Review Year<select value={filters.year} onChange={event => setFilters(current => ({ ...current, year: Number(event.target.value) }))} className={control}>{[...new Set([filters.year, ...(data.availableYears || [])])].sort((a, b) => b - a).map(item => <option key={item} value={item}>{item}</option>)}</select></label><label className="text-sm font-medium text-gray-700">Status<select value={filters.status} onChange={event => setFilters(current => ({ ...current, status: event.target.value }))} className={control}><option value="">Status</option><option value="SUBMITTED">Submitted</option><option value="NOT_SUBMITTED">Not Submitted</option></select></label></div><div className="mt-5 flex flex-wrap justify-end gap-3"><button type="button" onClick={clear} className="h-10 rounded-lg border border-gray-300 bg-white px-4 text-sm font-medium text-gray-700 hover:bg-gray-100">Clear Filters</button><AdminTypography.button type="submit" className="h-10 px-5">Apply Filters</AdminTypography.button></div></form>
    {loading ? <div className="py-10 text-gray-500">Loading performance reports…</div> : <div className="overflow-x-auto rounded-xl border border-gray-200"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-gray-700"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Company</th><th className="px-4 py-3">Review Type</th><th className="px-4 py-3">Year</th><th className="px-4 py-3">File</th><th className="px-4 py-3">Submitted On</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{data.rows?.length ? data.rows.map(row => <tr key={`${row.employeeId}-${row.reviewType}-${row.reviewYear}`} className="border-t border-gray-100 hover:bg-blue-50"><td className="px-4 py-3"><div className="font-medium">{row.employeeName}</div><div className="text-xs text-gray-500">{row.employeeEmail || '—'}</div></td><td className="px-4 py-3">{row.companyName}</td><td className="px-4 py-3">{row.reviewLabel}</td><td className="px-4 py-3">{row.reviewYear}</td><td className="max-w-56 truncate px-4 py-3" title={row.submission?.originalFilename}>{row.submission?.originalFilename || '—'}</td><td className="px-4 py-3">{formatDate(row.submission?.submittedAt)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${row.status === 'SUBMITTED' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-800'}`}>{row.status === 'SUBMITTED' ? 'Submitted' : 'Not Submitted'}</span></td><td className="px-4 py-3">{row.submission ? <div className="flex gap-3"><button onClick={() => startPreview(row)} className="text-blue-600 hover:text-blue-800"><FaEye className="mr-1 inline" />Preview</button><button onClick={() => download(row)} className="text-blue-600 hover:text-blue-800"><FaDownload className="mr-1 inline" />Download</button></div> : '—'}</td></tr>) : <tr><td colSpan="8" className="px-4 py-10 text-center text-gray-500">No applicable performance review records found for the selected filters.</td></tr>}</tbody></table></div>}
    {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className={`w-full rounded-xl bg-white p-6 shadow-xl ${preview.isPdf ? 'max-w-5xl' : 'max-w-lg'}`}><div className="flex items-start justify-between gap-4"><h2 className="text-lg font-semibold">Preview: {preview.filename}</h2><button onClick={closePreview} className="text-2xl leading-none text-gray-400">×</button></div>{preview.isPdf ? <iframe title={`Preview: ${preview.filename}`} src={preview.url} className="mt-4 h-[70vh] w-full rounded border" /> : <><p className="mt-4 text-gray-700">This file is a Microsoft Word document. The portal does not use an external document viewer, so browser preview depends on your browser’s installed Word support.</p><p className="mt-2 text-sm text-gray-500">If it does not open in your browser, download the document to view it safely.</p></>}<div className="mt-6 flex justify-end gap-3"><button onClick={closePreview} className="rounded border px-4 py-2">Close</button><a href={preview.url} target="_blank" rel="noreferrer" className="rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700">{preview.isPdf ? 'Open PDF' : 'Try Browser Preview'}</a></div></div></div>}
  </main>;
}
