import { useEffect, useRef, useState } from 'react';
import { FaDownload, FaFileWord, FaUpload } from 'react-icons/fa';
import EmpTypography from '../../components/emp/EmpTypography';
import { downloadProtectedPerformanceFile, getMyPerformanceReports, requestPerformanceReportReplacement, submitMyPerformanceReport, uploadMyPerformanceDraft } from '../../api/performanceReports';

const formatDate = value => value ? new Date(value).toLocaleString() : '—';

function Modal({ title, children, onClose }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div className="mb-4 flex items-start justify-between gap-4"><h2 className="text-lg font-semibold text-gray-900">{title}</h2><button onClick={onClose} className="text-2xl leading-none text-gray-400 hover:text-gray-700" aria-label="Close">×</button></div>{children}</div></div>;
}

export default function PerformanceReport() {
  const [data, setData] = useState(null); const [year, setYear] = useState(new Date().getFullYear()); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busyType, setBusyType] = useState(''); const [submitReview, setSubmitReview] = useState(null); const [requestReview, setRequestReview] = useState(null); const [reason, setReason] = useState(''); const inputs = useRef({});
  const load = async selectedYear => { setLoading(true); setError(''); try { const response = await getMyPerformanceReports(selectedYear); setData(response.data); if (response.data.reviewYear) setYear(response.data.reviewYear); } catch (err) { setError(err?.response?.data?.error || 'Unable to load performance review documents.'); } finally { setLoading(false); } };
  useEffect(() => { load(year); }, []);
  const download = async (path, filename) => { setError(''); try { await downloadProtectedPerformanceFile(path, filename); } catch (err) { setError(err.message || 'Download failed.'); } };
  const chooseUpload = review => inputs.current[review.reviewType]?.click();
  const upload = async (review, event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; const validPdf = /\.pdf$/i.test(file.name) && (!file.type || file.type === 'application/pdf'); if (!validPdf) { setError('Only PDF files are allowed for completed Performance Review uploads.'); return; } setBusyType(review.reviewType); setError(''); try { await uploadMyPerformanceDraft(review.reviewType, review.reviewYear, file); await load(review.reviewYear); } catch (err) { setError(err?.response?.data?.error || err.message || 'Upload failed.'); } finally { setBusyType(''); } };
  const submit = async () => { if (!submitReview?.reportId) return; setBusyType(submitReview.reviewType); setError(''); try { await submitMyPerformanceReport(submitReview.reportId); setSubmitReview(null); await load(submitReview.reviewYear); } catch (err) { setError(err?.response?.data?.error || 'Submission failed.'); } finally { setBusyType(''); } };
  const requestReplacement = async () => { if (!requestReview?.reportId) return; if (!reason.trim()) { setError('Reason for replacement is required.'); return; } setBusyType(requestReview.reviewType); setError(''); try { await requestPerformanceReportReplacement(requestReview.reportId, reason.trim()); setReason(''); setRequestReview(null); await load(requestReview.reviewYear); } catch (err) { setError(err?.response?.data?.error || 'Unable to submit replacement request.'); } finally { setBusyType(''); } };

  return <main className="flex-1 min-h-full bg-[#f5f6fa] p-8"><EmpTypography.label className="text-2xl text-gray-900">Performance Report</EmpTypography.label><p className="mt-2 text-gray-600">Download, complete, and submit your company performance review documents.</p>
    {error && <div role="alert" className="mt-5 rounded border border-red-200 bg-red-50 px-4 py-3 text-red-700">{error}</div>}
    {loading ? <div className="mt-8 text-gray-500">Loading performance review documents…</div> : !data?.company ? <div className="mt-8 rounded-lg border bg-white p-6 text-gray-600">{data?.message || 'Your company association is not available. Please contact HR.'}</div> : <>
      <div className="mt-6 flex flex-wrap items-center gap-3 rounded-lg border bg-white p-4"><span className="font-medium text-gray-800">Company: {data.company.name}</span><label className="ml-auto flex items-center gap-2 text-sm text-gray-700">Review Year<select value={year} onChange={event => { const nextYear = Number(event.target.value); setYear(nextYear); load(nextYear); }} className="rounded border px-3 py-2" aria-label="Review year">{(data.availableYears || [year]).map(item => <option key={item} value={item}>{item}</option>)}</select></label></div>
      {!data.reviews?.length ? <div className="mt-6 rounded-lg border bg-white p-6 text-gray-600">Performance review templates are not available for {year}.</div> : <div className="mt-6 grid gap-5 lg:grid-cols-2">{data.reviews.map(review => {
        const submission = review.submission; const draft = review.draft; const request = review.replacementRequest; const busy = busyType === review.reviewType; const approved = request?.status === 'approved'; const pending = request?.status === 'pending';
        const uploadAllowed = !submission || approved; const uploadLabel = busy ? 'Uploading…' : draft ? 'Choose Different Document' : submission ? 'Replace Document' : 'Upload Completed Document';
        return <section key={review.reviewType} className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><EmpTypography.label className="text-lg text-gray-900">{review.reviewLabel}</EmpTypography.label><p className="mt-1 text-sm text-gray-600">Review Period: {review.reviewMonth} {review.reviewYear}</p></div><span className={`rounded-full px-3 py-1 text-sm font-medium ${submission ? 'bg-green-100 text-green-700' : draft ? 'bg-blue-100 text-blue-700' : 'bg-amber-100 text-amber-800'}`}>{submission ? 'Submitted' : draft ? 'Ready to Submit' : 'Not Submitted'}</span></div>
          <div className="mt-5 rounded-lg bg-gray-50 p-4 text-sm text-gray-700"><div className="flex items-center gap-2"><FaFileWord className="text-blue-600" /><span className="truncate">{review.templateFilename}</span></div></div>
          <div className="mt-4 flex flex-wrap gap-3"><EmpTypography.button variant="primary" onClick={() => download(`/performance-reports/me/templates/${review.templateId}/download`, review.templateFilename)}><FaDownload className="mr-2 inline" />Download Template</EmpTypography.button>{uploadAllowed && <><input ref={node => { inputs.current[review.reviewType] = node; }} type="file" accept=".pdf,application/pdf" className="hidden" onChange={event => upload(review, event)} /><EmpTypography.button variant="primary" disabled={busy} onClick={() => chooseUpload(review)}><FaUpload className="mr-2 inline" />{uploadLabel}</EmpTypography.button></>}</div>
          {uploadAllowed && <p className="mt-3 text-sm text-gray-600">Download the Word template, complete your Performance Review, save or export it as a PDF, and upload the completed PDF here. Only PDF files are accepted.</p>}
          {draft && <div className="mt-5 border-t pt-4 text-sm text-gray-700"><div>Prepared Document: <span className="font-medium">{draft.originalFilename}</span></div><div className="mt-1">Uploaded: {formatDate(draft.uploadedAt)}</div><EmpTypography.button className="mt-3" variant="primary" disabled={busy} onClick={() => setSubmitReview(review)}>Submit</EmpTypography.button></div>}
          {submission && <div className="mt-5 border-t pt-4 text-sm text-gray-700"><div>Submitted File: <span className="font-medium">{submission.originalFilename}</span></div><div className="mt-1">Submitted On: {formatDate(submission.submittedAt)}</div><button className="mt-3 text-blue-600 hover:text-blue-800" onClick={() => download(`/performance-reports/me/submissions/${submission.id}/download`, submission.originalFilename)}><FaDownload className="mr-1 inline" />Download Submitted File</button>
            <div className="mt-4">{pending ? <span className="rounded bg-amber-100 px-3 py-2 text-amber-800">Replacement Request: Pending</span> : approved ? <span className="rounded bg-green-100 px-3 py-2 text-green-800">Replacement Request: Approved — upload the corrected document, then submit it.</span> : <EmpTypography.button variant="primary" onClick={() => { setRequestReview(review); setReason(''); }}>Request Replacement</EmpTypography.button>}{request?.status === 'rejected' && <p className="mt-2 text-red-700">Replacement Request: Rejected. You may submit a new request if needed.</p>}</div>
          </div>}
        </section>;
      })}</div>}
    </>}
    {submitReview && <Modal title="Submit Performance Review?" onClose={() => setSubmitReview(null)}><p className="text-gray-700">After submission, you cannot replace this document unless Root Admin approves a replacement request.</p><div className="mt-6 flex justify-end gap-3"><button onClick={() => setSubmitReview(null)} className="rounded border px-4 py-2 text-gray-700">Cancel</button><EmpTypography.button variant="primary" disabled={busyType === submitReview.reviewType} onClick={submit}>Submit</EmpTypography.button></div></Modal>}
    {requestReview && <Modal title="Request Performance Report Replacement" onClose={() => setRequestReview(null)}><p className="mb-3 text-sm text-gray-600">Please explain why you need to replace the submitted document.</p><label className="block text-sm font-medium text-gray-800">Reason for Replacement <span className="text-red-600">*</span><textarea value={reason} onChange={event => setReason(event.target.value)} rows="5" className="mt-1 w-full rounded border p-3" placeholder="Explain why the submitted document needs to be replaced." /></label><div className="mt-6 flex justify-end gap-3"><button onClick={() => setRequestReview(null)} className="rounded border px-4 py-2 text-gray-700">Cancel</button><EmpTypography.button variant="primary" disabled={busyType === requestReview.reviewType} onClick={requestReplacement}>Submit Request</EmpTypography.button></div></Modal>}
  </main>;
}
