-- Additive migration for Vendor billing metadata and complete invoice records.
-- Existing rows remain valid because every new field is nullable or has a default.

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "employeeName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "companyName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "templateName" VARCHAR(255) DEFAULT 'standard';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS project_id INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "projectName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS client_id INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "clientName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS vendor_id INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "vendorName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS prime_vendor_id INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "primeVendorName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billToType" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billToId" INTEGER;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billToCompany" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billingContactName" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billingEmail" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billingAddress" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "invoiceDate" DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billingFromDate" DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "billingToDate" DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "poNumber" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "paymentTerms" VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "dueDate" DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS currency VARCHAR(20);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total NUMERIC(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "balanceDue" NUMERIC(12,2) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "pdfPath" VARCHAR(1024);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "pdfVersion" INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS invoice_items (
  id SERIAL PRIMARY KEY,
  invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  hours NUMERIC(12,2) NOT NULL DEFAULT 0,
  rate NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
