-- Admin Dashboard Database Schema (PostgreSQL)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "admin_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar,
  "phone" varchar NOT NULL,
  "is_whatsapp_same" boolean,
  "whatsapp_number" varchar,
  "role" varchar DEFAULT 'employee'
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL CHECK (role IN ('Admin', 'Employee')),
  "status" varchar DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "employees" (
  "employee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int,
  "relation_type" varchar NOT NULL,
  "profile_image_url" text,
  "first_name" varchar NOT NULL,
  "middle_name" varchar,
  "last_name" varchar NOT NULL,
  "email" varchar,
  "phone" varchar,
  "is_whatsapp_same" boolean,
  "whatsapp_number" varchar,
  "dob" date,
  "marital_status" varchar,
  "nationality" varchar,
  "passport_number" varchar,
  "passport_expiry" date,
  "ssn" varchar,
  "sin" varchar,
  "ni" varchar,
  "tfn" varchar,
  "pan" varchar,
  "aadhaar" varchar,
  "occupation" varchar,
  "visa_type" varchar,
  "custom_visa_type" varchar,
  "visa_expiry" date,
  "dl_number" varchar,
  "dl_state" varchar,
  "dl_expiry" date,
  "is_address_same" boolean,
  "address_id" int,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "address" (
  "address_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "label" varchar,
  "street" varchar,
  "city" varchar,
  "state" varchar,
  "zip" varchar,
  "country" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "kid" (
  "kid_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "first_name" varchar,
  "middle_name" varchar,
  "last_name" varchar,
  "dob" date,
  "nationality" varchar,
  "passport_number" varchar,
  "passport_expiry" date,
  "ssn" varchar,  
  "sin" varchar,
  "ni" varchar,
  "tfn" varchar,
  "pan" varchar,
  "aadhaar" varchar,
  "visa_type" varchar,
  "custom_visa_type" varchar,
  "visa_expiry" date,
  "address_same" boolean,
  "kid_address_id" int,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "emergency_contact" (
  "emergency_contact_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "first_name" varchar,
  "middle_name" varchar,
  "last_name" varchar,
  "phone" varchar NOT NULL,
  "email" varchar,
  "relationship" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "onboarding_files" (
  "onboarding_file_id" serial PRIMARY KEY,
  "employee_id" int NOT NULL,
  "template_name" varchar NOT NULL,
  "template_url" text,
  "uploaded_file_url" text,
  "uploaded_by_user_id" int,
  "status" varchar DEFAULT 'pending',
  "remarks" text,
  "bank_name" varchar,
  "account_number" varchar,
  "routing_number" varchar,
  "account_type" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "user_family" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "relation" varchar,
  "name" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "insurance_coverage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "family_member_id" int,
  "name" varchar,
  "medical" boolean,
  "vision" boolean,
  "dental" boolean,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "work_profiles" (
  "work_profile_id" serial PRIMARY KEY,
  "employee_id" int,
  "in_project" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "present_employers" (
  "present_employer_id" serial PRIMARY KEY,
  "work_profile_id" int,
  "name" varchar,
  "designation" varchar,
  "start_date" date,
  "end_date" date,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "present_employer_uploads" (
  "present_employer_upload_id" serial PRIMARY KEY,
  "present_employer_id" int,
  "file_name" varchar,
  "file_url" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "previous_employers" (
  "previous_employer_id" serial PRIMARY KEY,
  "work_profile_id" int,
  "name" varchar,
  "designation" varchar,
  "start_date" date,
  "end_date" date,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "previous_employer_uploads" (
  "previous_employer_upload_id" serial PRIMARY KEY,
  "previous_employer_id" int,
  "file_name" varchar,
  "file_url" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "work_clients" (
  "work_client_id" serial PRIMARY KEY,
  "work_profile_id" int,
  "name" varchar,
  "start_date" date,
  "end_date" date,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "client_information" (
  "client_information_id" serial PRIMARY KEY,
  "work_profile_id" int,
  "name" varchar,
  "address" varchar,
  "start_date" date,
  "end_date" date,
  "work_email" varchar,
  "manager_email" varchar,
  "manager_phone" varchar,
  "remote_work_location" varchar,
  "client_vendor_radio" varchar,
  "client_prime_radio" varchar,
  "client_vendor_name" varchar,
  "client_prime_name" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "client_uploads" (
  "client_upload_id" serial PRIMARY KEY,
  "client_information_id" int,
  "file_name" varchar,
  "file_url" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "vendor_information" (
  "vendor_information_id" serial PRIMARY KEY,
  "work_profile_id" int,
  "name" varchar,
  "address" varchar,
  "vendor_person_name" varchar,
  "start_date" date,
  "end_date" date,
  "email" varchar,
  "finc" varchar,
  "phone" varchar,
  "vendor_client_radio" varchar,
  "vendor_prime_radio" varchar,
  "vendor_client_name" varchar,
  "vendor_prime_name" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "vendor_uploads" (
  "vendor_upload_id" serial PRIMARY KEY,
  "vendor_information_id" int,
  "file_name" varchar,
  "file_url" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "prime_vendor_information" (
  "prime_vendor_information_id" serial PRIMARY KEY,
  "work_profile_id" int,
  "name" varchar,
  "address" varchar,
  "email" varchar,
  "phone" varchar,
  "start_date" date,
  "end_date" date,
  "prime_client_radio" varchar,
  "prime_vendor_radio" varchar,
  "prime_client_name" varchar,
  "prime_vendor_name" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "prime_vendor_uploads" (
  "prime_vendor_upload_id" serial PRIMARY KEY,
  "prime_vendor_information_id" int,
  "file_name" varchar,
  "file_url" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "role_sections" (
  "role_section_id" serial PRIMARY KEY,
  "employee_id" int,
  "role" varchar NOT NULL,
  "description" text,
  "skills" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "resume_uploads" (
  "resume_upload_id" serial PRIMARY KEY,
  "role_section_id" int,
  "file_name" varchar,
  "file_type" varchar,
  "file_size" integer,
  "file_url" text,
  "upload_date" timestamp DEFAULT 'now()',
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "cv_uploads" (
  "cv_upload_id" serial PRIMARY KEY,
  "role_section_id" int,
  "file_name" varchar,
  "file_type" varchar,
  "file_size" integer,
  "file_url" text,
  "upload_date" timestamp DEFAULT 'now()',
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "educations" (
  "education_id" serial PRIMARY KEY,
  "employee_id" int,
  "education_level" varchar(255),
  "degree" varchar,
  "university" varchar,
  "major" varchar,
  "start_date" date,
  "end_date" date,
  "street" varchar,
  "city" varchar,
  "state" varchar,
  "zip_code" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "education_uploads" (
  "id" serial PRIMARY KEY,
  "education_id" int,
  "file_name" varchar,
  "file_url" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "certifications" (
  "certification_id" serial PRIMARY KEY,
  "education_id" int,
  "name" varchar,
  "org" varchar,
  "start_date" date,
  "end_date" date,
  "description" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "documents" (
  "document_id" serial PRIMARY KEY,
  "employee_id" int NOT NULL,
  "name" varchar NOT NULL,
  "section" varchar NOT NULL,
  "category" varchar,
  "file_name" varchar,
  "file_url" text NOT NULL,
  "file_type" varchar,
  "file_size" integer,
  "expiry_date" date,
  "uploaded_by" varchar,
  "uploaded_by_user_id" int,
  "status" varchar DEFAULT 'pending',
  "modified_by" varchar,
  "signed_copy_url" text,
  "locked" boolean DEFAULT false,
  "override_requested" boolean DEFAULT false,
  "override_granted" boolean DEFAULT false,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "form_status" (
  "id" serial PRIMARY KEY,
  "employee_id" int NOT NULL,
  "section_key" varchar NOT NULL,
  "status" varchar DEFAULT 'saved' CHECK (status IN ('saved', 'submitted', 'pending_approval', 'approved', 'rejected')),
  "last_action_by" int,
  "last_action_at" timestamp DEFAULT 'now()',
  "remarks" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "modification_requests" (
  "request_id" serial PRIMARY KEY,
  "employee_id" int,
  "section_key" varchar NOT NULL,
  "requested_by" int,
  "requested_reason" text NOT NULL,
  "reviewed_by" int,
  "review_decision" varchar DEFAULT 'pending',
  "review_comments" text,
  "created_at" timestamp DEFAULT 'now()',
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "employee_settings" (
  "id" uuid PRIMARY KEY NOT NULL,
  "employee_id" int,
  "last_email_update" timestamp,
  "last_password_update" timestamp,
  "prev_role" varchar(100),
  "prev_desc" text,
  "project_role" varchar(100),
  "job_desc" text,
  "training_modules" text,
  "certifications" text,
  "updated_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "employee_feedback" (
  "feedback_id" serial PRIMARY KEY,
  "employee_id" int NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "projects" (
  "project_id" serial PRIMARY KEY,
  "project_name" varchar(255) NOT NULL,
  "description" text,
  "start_date" date,
  "end_date" date,
  "client_id" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "tasks" (
  "task_id" serial PRIMARY KEY,
  "task_name" varchar(255) NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "timesheets" (
  "timesheet_id" serial PRIMARY KEY,
  "employee_id" int NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "submission_date" timestamp DEFAULT (now()),
  "approval_status" varchar(50) DEFAULT 'pending',
  "total_hours" decimal(5,2) DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "timesheet_entries" (
  "entry_id" serial PRIMARY KEY,
  "timesheet_id" int NOT NULL,
  "project_id" int,
  "task_id" int,
  "work_date" date NOT NULL,
  "hours_worked" decimal(5,2) DEFAULT 0,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "leave_requests" (
  "leave_request_id" serial PRIMARY KEY,
  "employee_id" int NOT NULL,
  "leave_type" varchar(100) NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "number_of_days" decimal(4,1),
  "reason" text,
  "status" varchar(50) DEFAULT 'pending',
  "approval_date" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "approvals" (
  "approval_id" serial PRIMARY KEY,
  "approver_id" int NOT NULL,
  "timesheet_id" int,
  "leave_request_id" int,
  "approval_status" varchar(50) DEFAULT 'pending',
  "comments" text,
  "approval_date" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "uploaded_timesheets" (
  "upload_id" serial PRIMARY KEY,
  "timesheet_id" int NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "file_url" text NOT NULL,
  "file_type" varchar(50),
  "uploaded_by" int NOT NULL,
  "upload_date" timestamp DEFAULT 'now()',
  "extracted_status" varchar(50) DEFAULT 'pending',
  "extraction_notes" text,
  "client_hours" decimal(5,2),
  "client_project" varchar(255),
  "client_role" varchar(100),
  "client_notes" text,
  "is_reference" boolean DEFAULT true,
  "created_at" timestamp DEFAULT 'now()'
);

COMMENT ON COLUMN "admin_users"."role" IS 'ENUM: employee | admin | super_user';

COMMENT ON COLUMN "employees"."relation_type" IS 'ENUM: employee | spouse';

COMMENT ON COLUMN "employees"."marital_status" IS 'For employee only; NULL for spouse';

COMMENT ON COLUMN "employees"."occupation" IS 'For spouse only, can be NULL for employee';

COMMENT ON COLUMN "employees"."visa_type" IS 'ENUM: H1B | L1 | F1 | B1/B2 | J1 | H4 | Green Card | US Citizen | Other';

COMMENT ON COLUMN "employees"."is_address_same" IS 'true if same as employee address';

COMMENT ON COLUMN "onboarding_files"."template_url" IS 'Admin-uploaded blank template';

COMMENT ON COLUMN "onboarding_files"."uploaded_file_url" IS 'Employee-signed version reuploaded';

COMMENT ON COLUMN "onboarding_files"."status" IS 'pending | signed | approved';

COMMENT ON COLUMN "documents"."name" IS 'Display name shown in UI, e.g. Driving License';

COMMENT ON COLUMN "documents"."section" IS 'ENUM: personal | education | work | visa | onboarding | other';

COMMENT ON COLUMN "documents"."category" IS 'Document classification or sub-type';

COMMENT ON COLUMN "documents"."uploaded_by" IS 'employee | admin | system';

COMMENT ON COLUMN "documents"."status" IS 'pending | approved | rejected | signed';

COMMENT ON COLUMN "documents"."locked" IS 'If true, employee cannot modify';

COMMENT ON COLUMN "form_status"."section_key" IS 'e.g., personal, education, work, onboarding, visa';

COMMENT ON COLUMN "form_status"."status" IS 'ENUM: draft | submitted | locked | modification_requested | modification_approved | modification_rejected';

COMMENT ON COLUMN "form_status"."last_action_by" IS 'who performed the last action (emp/admin)';

COMMENT ON COLUMN "form_status"."remarks" IS 'Admin notes or employee request reason';

COMMENT ON COLUMN "modification_requests"."requested_by" IS 'Employee ID';

COMMENT ON COLUMN "modification_requests"."review_decision" IS 'pending | approved | rejected';

COMMENT ON COLUMN "employee_feedback"."message" IS 'Employee suggestion or feedback';

COMMENT ON COLUMN "timesheets"."approval_status" IS 'ENUM: pending | approved | rejected';

COMMENT ON COLUMN "leave_requests"."leave_type" IS 'ENUM: annual | sick | unpaid | others';

COMMENT ON COLUMN "leave_requests"."status" IS 'ENUM: pending | approved | rejected | cancelled';

COMMENT ON COLUMN "approvals"."approval_status" IS 'ENUM: pending | approved | rejected';

COMMENT ON COLUMN "uploaded_timesheets"."file_url" IS 'S3 or local file path';

COMMENT ON COLUMN "uploaded_timesheets"."file_type" IS 'pdf | png | jpg';

COMMENT ON COLUMN "uploaded_timesheets"."extracted_status" IS 'pending | success | failed';

COMMENT ON COLUMN "uploaded_timesheets"."is_reference" IS 'True if this is a client reference copy';

ALTER TABLE "employees" ADD FOREIGN KEY ("person_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "employees" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("address_id");

ALTER TABLE "address" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "kid" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "kid" ADD FOREIGN KEY ("kid_address_id") REFERENCES "address" ("address_id");

ALTER TABLE "emergency_contact" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "onboarding_files" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "onboarding_files" ADD FOREIGN KEY ("uploaded_by_user_id") REFERENCES "admin_users" ("id");

ALTER TABLE "user_family" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "insurance_coverage" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "insurance_coverage" ADD FOREIGN KEY ("family_member_id") REFERENCES "user_family" ("id");

ALTER TABLE "work_profiles" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "present_employers" ADD FOREIGN KEY ("work_profile_id") REFERENCES "work_profiles" ("work_profile_id");

ALTER TABLE "present_employer_uploads" ADD FOREIGN KEY ("present_employer_id") REFERENCES "present_employers" ("present_employer_id");

ALTER TABLE "previous_employers" ADD FOREIGN KEY ("work_profile_id") REFERENCES "previous_employers" ("work_profile_id");

ALTER TABLE "previous_employer_uploads" ADD FOREIGN KEY ("previous_employer_id") REFERENCES "previous_employers" ("previous_employer_id");

ALTER TABLE "work_clients" ADD FOREIGN KEY ("work_profile_id") REFERENCES "work_profiles" ("work_profile_id");

ALTER TABLE "client_information" ADD FOREIGN KEY ("work_profile_id") REFERENCES "work_profiles" ("work_profile_id");

ALTER TABLE "client_uploads" ADD FOREIGN KEY ("client_information_id") REFERENCES "client_information" ("client_information_id");

ALTER TABLE "vendor_information" ADD FOREIGN KEY ("work_profile_id") REFERENCES "work_profiles" ("work_profile_id");

ALTER TABLE "vendor_uploads" ADD FOREIGN KEY ("vendor_information_id") REFERENCES "vendor_information" ("vendor_information_id");

ALTER TABLE "prime_vendor_information" ADD FOREIGN KEY ("work_profile_id") REFERENCES "work_profiles" ("work_profile_id");

ALTER TABLE "prime_vendor_uploads" ADD FOREIGN KEY ("prime_vendor_information_id") REFERENCES "prime_vendor_information" ("prime_vendor_information_id");

ALTER TABLE "role_sections" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "resume_uploads" ADD FOREIGN KEY ("role_section_id") REFERENCES "role_sections" ("role_section_id");

ALTER TABLE "cv_uploads" ADD FOREIGN KEY ("role_section_id") REFERENCES "role_sections" ("role_section_id");

ALTER TABLE "educations" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "education_uploads" ADD FOREIGN KEY ("education_id") REFERENCES "educations" ("education_id");

ALTER TABLE "certifications" ADD FOREIGN KEY ("education_id") REFERENCES "educations" ("education_id");

ALTER TABLE "documents" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "documents" ADD FOREIGN KEY ("uploaded_by_user_id") REFERENCES "admin_users" ("id");

ALTER TABLE "form_status" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "form_status" ADD FOREIGN KEY ("last_action_by") REFERENCES "admin_users" ("id");

ALTER TABLE "modification_requests" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "modification_requests" ADD FOREIGN KEY ("requested_by") REFERENCES "admin_users" ("id");

ALTER TABLE "modification_requests" ADD FOREIGN KEY ("reviewed_by") REFERENCES "admin_users" ("id");

ALTER TABLE "employee_settings" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "employee_feedback" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "timesheets" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "timesheet_entries" ADD FOREIGN KEY ("timesheet_id") REFERENCES "timesheets" ("timesheet_id");

ALTER TABLE "timesheet_entries" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id");

ALTER TABLE "timesheet_entries" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("task_id");

ALTER TABLE "leave_requests" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "approvals" ADD FOREIGN KEY ("approver_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "approvals" ADD FOREIGN KEY ("timesheet_id") REFERENCES "timesheets" ("timesheet_id");

ALTER TABLE "approvals" ADD FOREIGN KEY ("leave_request_id") REFERENCES "leave_requests" ("leave_request_id");

ALTER TABLE "uploaded_timesheets" ADD FOREIGN KEY ("timesheet_id") REFERENCES "timesheets" ("timesheet_id");

ALTER TABLE "uploaded_timesheets" ADD FOREIGN KEY ("uploaded_by") REFERENCES "employees" ("employee_id");

CREATE TABLE "admin_audit_logs" (
  "log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_user_id" int REFERENCES "users"("user_id"),
  "action_type" varchar NOT NULL CHECK (action_type IN ('APPROVE', 'REJECT', 'UPDATE', 'DELETE')),
  "table_name" varchar,
  "record_id" int,
  "old_value" text,
  "new_value" text,
  "description" text,
  "created_at" timestamp DEFAULT 'now()'
);
