const { DataTypes } = require('sequelize');
const sequelize = require('./db');

const Invoice = sequelize.define('Invoice', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  employee_id: { type: DataTypes.INTEGER, allowNull: false },
  employeeName: DataTypes.STRING,
  company_id: DataTypes.INTEGER,
  companyName: DataTypes.STRING,
  templateName: { type: DataTypes.STRING, defaultValue: 'standard' },
  project_id: DataTypes.INTEGER,
  projectName: DataTypes.STRING,
  client_id: DataTypes.INTEGER,
  clientName: DataTypes.STRING,
  vendor_id: DataTypes.INTEGER,
  vendorName: DataTypes.STRING,
  prime_vendor_id: DataTypes.INTEGER,
  primeVendorName: DataTypes.STRING,
  billToType: DataTypes.STRING,
  billToId: DataTypes.INTEGER,
  billToCompany: DataTypes.STRING,
  billingContactName: DataTypes.STRING,
  billingEmail: DataTypes.STRING,
  billingAddress: DataTypes.TEXT,
  invoiceDate: DataTypes.DATEONLY,
  billingFromDate: DataTypes.DATEONLY,
  billingToDate: DataTypes.DATEONLY,
  poNumber: DataTypes.STRING,
  paymentTerms: DataTypes.STRING,
  customPaymentDays: DataTypes.INTEGER,
  dueDate: DataTypes.DATEONLY,
  currency: DataTypes.STRING,
  subtotal: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  total: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  balanceDue: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  invoiceNumber: DataTypes.STRING,
  status: { type: DataTypes.STRING, defaultValue: 'Draft' },
  generatedDate: DataTypes.DATEONLY,
  url: DataTypes.STRING,
  filename: DataTypes.STRING,
  originalName: DataTypes.STRING,
  pdfPath: DataTypes.STRING,
  pdfVersion: { type: DataTypes.INTEGER, defaultValue: 0 },
  createdBy: DataTypes.STRING,
  updatedBy: DataTypes.STRING,
}, {
  tableName: 'invoices',
  freezeTableName: true,
  timestamps: true,
});

module.exports = Invoice;
